### PR TITLE
Copy certificates to the /etc/ssl/certs and run openssl rehash for the run image

### LINKED ISSUE #73: The run image is missing hashed file names of the root certificates
## Expected Behavior

OpenSSL library should work.

## Current Behavior

```console
$ docker run -it paketobuildpacks/run-jammy-tiny:latest openssl s_client -verify_return_error -brief api.nasa.gov:443                                           130
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify error:num=20:unable to get local issuer certificate
4007CBB13B7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883:
```

## Possible Solution

Run either `update-ca-certificates` or `openssl rehash` after `install-certs.sh` script execution.

## Steps to Reproduce

1. Run the docker command from above

## Motivations

During SSL negotiation, OpenSSL receives a server certificate and then calculates the hash of the certificate and uses the hash to find the appropriate certificate in the `CERTDIR` folder (`/etc/ssl/certs` by default)

### PR DESCRIPTION
**Pull request by pbusko**
## Summary

Fixes #73 

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by robdimsdale** [comment]
Thanks @pbusko for submitting this!

These changes look good and I'm happy to merge. I'm not familiar with `openssl rehash`, so can you help me understand what aspects of SSL certificate usage (if any) were functioning correctly before this change?

From https://www.openssl.org/docs/man1.1.1/man1/rehash.html:

> rehash scans directories and calculates a hash value of each .pem, .crt, .cer, or .crl file in the specified directory list and creates symbolic links for each file, where the name of the link is the hash value. (If the platform does not support symbolic links, a copy is made.) This utility is useful as many programs that use OpenSSL require directories to be set up like this in order to find certificates.
>
> If any directories are named on the command line, then those are processed in turn. If not, then the SSL_CERT_DIR environment variable is consulted; this should be a colon-separated list of directories, like the Unix PATH variable. If that is not set then the default directory (installation-specific but often /usr/local/ssl/certs) is processed.

This suggests to me that some applications/tools don't require the hashed directories, and so worked before this PR, but others rely on these hashed directories and hence we need this change.

It also indicates me to me that setting `SSL_CERT_DIR` could be an alternative to providing the directory to `openssl rehash <dir>`. But I think the current approach of providing the directory is logical and clear.

**Comment by robdimsdale** [comment]
Also @pbusko do we need to add this to the [Bionic Tiny Stack](https://github.com/paketo-buildpacks/bionic-tiny-stack/) too?

**Review by robdimsdale — APPROVED** [review]

**Comment by arjun024** [comment]
I wonder why the entire script can't be replaced with `update-ca-certificates --etccertsdir X --certsdir Y`?

**Comment by robdimsdale** [comment]
@pbusko thanks for clarifying. This is great - I'm happy to merge.

Would you be willing to open a similar PR for the bionic tiny stack?

**Comment by pbusko** [comment]
> @pbusko thanks for clarifying. This is great - I'm happy to merge.
> 
> Would you be willing to open a similar PR for the bionic tiny stack?

Done https://github.com/paketo-buildpacks/bionic-tiny-stack/pull/96

**Pull request merged**
